### ISSUE TITLE
Doesn't work with ubisoft download

### ISSUE THREAD

**Issue by garygumdrops** [Eisenmonoxid/S7Patcher#3]
Unfortunately doesn't work with the version downloaded/bought from Ubisoft (not steam).

**Comment by Eisenmonoxid** [comment]
Hey,
Yes, I myself only own the Steam Gold Edition, everything else is untested. Maybe if you could upload your Settlers7R.exe, i could take a look at it.

Also, the S7Patcher will only work if you already bought the DLC when it was still available - it will not unlock it for other releases.

Regards,
Eisenmonoxid

**Comment by garygumdrops** [comment]
[The Settlers7.zip](https://github.com/user-attachments/files/18262757/The.Settlers7.zip)

I've uploaded a zip with the .exe from my version. I would have downloaded the DLC ages ago but can't remember when.

If stream still had the gold edition I'd download that if I thought I could get this working but they only have the history edition (whatever that is).

**Comment by Eisenmonoxid** [comment]
It seems that this is the wrong executable - It is only the games' launcher. You should find another executable in your game installation folder that is called "Settlers7R.exe". Try the S7Patcher on that and please report back.

**Comment by garygumdrops** [comment]
That's the only executable I can find on the whole PC using 'Settlers*.exe' as a search.

It's in C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\games\Settlers 7

It does run up the game and not through the uplay launcher if I run it.

I'm looking at the history edition which seems just an updated version to run on Windoze 10. That's the version on Steam and it's only a fiver at the moment. I might download that tomorrow through Steam and try it as not much to lose. It's the 'chronicles of tandria' that I miss the most and I could waste a whole weekend playing that.

**Comment by Eisenmonoxid** [comment]
Yes, buying the History Edition is probably the easiest solution. I wish you fun with the DLC campaign, should also probably replay it myself ;)
